app/posts/blueprint.py
from flask import Blueprint
from flask import render_template

posts_python = Blueprint('posts_python', __name__, template_folder='templates')
posts_flask = Blueprint('posts_flask', __name__, template_folder='templates')

@posts_python.route('/')
def python():
    return render_template('posts_python/python.html')

@posts_flask.route('/')
def flask():
    return render_template('posts_flask/flask.html')

app/templates/about_me.html
{% extends 'index.html' %}


{% block title %}
    {{ post}}
{% endblock title %}
    
    

{% block content %}
<div class="tab-pane fade active show" id="tabs-1-2">
    <div class="content-box hide-on-modal">
      <div class="content-box-inner">
        <div class="row align-items-center row-30 row-md-30">
          <div class="col-12 col-md-6 col-lg-7">
            <figure><img src="{{ url_for('static', filename='images/iam.jpeg') }}" alt="" width="350" height="450">
            </figure>
          </div>
          <div class="col-12 col-md-6 col-lg-5">
            <h5><p class="subtitle">My first experience in programming</p></h5>
            <p></p>I began to program with the university, programmed AVR (Arduino) microcontrollers, then passed to ARM (STM32). During study I did theses (desktop applications), to other students in the language C# Unity, WPF. 
              Web began to study technologies in 2020, having chosen resolutely to replace a profession.
            </p>
            <h5><p class="subtitle">What I know</p></h5>
            <p>Python, Django/Flask, HTML/CSS, JavaScript/Jquery, React, Postgres, Mysql</p>
            <p>P.S. Working on Node.js, MongoDB and Machine Learning.</p>
          </div>
        </div>
      </div><a class="close-content-box" href="/">x</a>
    </div>
    <div class="modal slideUp" id="modal-about-us" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="content-box">
            <div class="content-box-inner">
              <div class="row">
                <div class="col-12">
                  <h3>A Few Words About Me</h3>
                  <p>Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae. Rat voleneni ullam corporis suscipit labasic ut aliquidea commodi consequatur. Aquis autem vel eum iure reprehenderit, muytasas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae.</p>
                  <p>Rat voleneni ullam corporis suscipit labasic ut aliquidea commodi consequatur. Aquis autem vel eum iure reprehenderit. Asas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae. Rat voleneni ullam corporis suscipit labasic ut aliquidea commodi consequatur. Aquis autem vel eum iure reprehenderit, muytasas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempo. Asas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae. Rat voleneni ullam corporis suscipit labasic ut aliquidea</p>
                </div>
              </div>
            </div><a class="close-modal-content-box" href="#" data-dismiss="modal">x</a>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}
    

app/templates/category_detail.html
{% extends 'index.html' %}


{% block title %}
    {{ post}}
{% endblock title %}
    
    

{% block content %}
    <div class="tab-content">
        <div class="gallery-wrap">
            <div class="gallery-wrap-inner">
            <h4>Jobs: {{ category.title }}</h4>
            <div class="dots-custom-portrait"></div><a class="back-to-gallery button-link button-link-icon" href="/"><span class="novi-icon icon icon-primary fa fa-angle-left"></span><span>back to gallery</span></a>
            </div>
            <div class="gallery-wrap-inner">
            <!-- Owl Carousel-->
            <div class="owl-carousel owl-gallery" data-items="1" data-dots="true" data-nav="false" data-stage-padding="0" data-loop="false" data-margin="0" data-mouse-drag="false" data-lightgallery="group" data-pagination-class=".dots-custom-portrait">
                {% for post in posts %}
                
                <figure>
                    <div class="text-center mb-4">
                        <h3>{{ post.title }}</h3>
                    </div>
                    {% if post.type in ['jpg', 'jpeg', 'png', 'svg', 'gif'] %}
                    <img src="static/{{post.path}}" alt=""/>
                    {% else %}
                    <video width="720" height="480" controls>
                        <source src={{ url_for('static', filename="demo.mp4") }} type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                    {% endif %}
                    <div class="button-item text-center my-2">
                        <a class="btn1 mt-2 align-middle" href="https://scrap-job.herokuapp.com/">Перейти на сайт</a>
                    </div>
                </figure>
                {% endfor %}
                <!-- <figure><img src="{{ url_for('static', filename='images/django1.png') }}" alt=""/>
                </figure>
                <a class="gallery-item" href="{{ url_for('static', filename='images/gallery-fashion-01-970x524.jpg') }}" data-lightgallery="item">
                <figure><img src="{{ url_for('static', filename='images/gallery-fashion-01-970x524.jpg') }}" alt="" width="970" height="524"/>
                </figure>
                <a class="gallery-item" href="{{ url_for('static', filename='images/gallery-fashion-02-970x524.jpg') }}" data-lightgallery="item">
                <figure><img src="{{ url_for('static', filename='images/gallery-fashion-02-970x524.jpg') }}" alt="" width="970" height="524"/>
                </figure>
                <a class="gallery-item" href="{{ url_for('static', filename='images/gallery-fashion-04-970x524.jpg') }}" data-lightgallery="item">
                <figure><img src="{{ url_for('static', filename='images/gallery-fashion-04-970x524.jpg') }}" alt="" width="970" height="524"/>
                </figure>
                <a class="gallery-item" href="{{ url_for('static', filename='images/gallery-fashion-05-970x524.jpg') }}" data-lightgallery="item">
                <figure><img src="{{ url_for('static', filename='images/gallery-fashion-05-970x524.jpg') }}" alt="" width="970" height="524"/>
                </figure>
                <a class="gallery-item" href="{{ url_for('static', filename='images/gallery-fashion-06-970x524.jpg') }}" data-lightgallery="item">
                <figure><img src="{{ url_for('static', filename='images/gallery-fashion-06-970x524.jpg') }}" alt="" width="970" height="524"/>
                </figure>
                <a class="gallery-item" href="{{ url_for('static', filename='images/gallery-fashion-07-970x524.jpg') }}" data-lightgallery="item">
                <figure><img src="{{ url_for('static', filename='images/gallery-fashion-07-970x524.jpg') }}" alt="" width="970" height="524"/>
                </figure>
                <a class="gallery-item" href="{{ url_for('static', filename='images/gallery-fashion-08-970x524.jpg') }}" data-lightgallery="item">
                <figure><img src="{{ url_for('static', filename='images/gallery-fashion-08-970x524.jpg') }}" alt="" width="970" height="524"/>
                </figure> -->
            </div>
            </div>
        </div>
    </div>

{% endblock content %}
    

app/templates/contacts.html
{% extends 'index.html' %}


{% block title %}
    {{ post}}
{% endblock title %}
    
    

{% block content %}
<div class="tab-pane fade active show" id="tabs-1-4">
    <div class="content-box hide-on-modal">
      <div class="row row-30 justify-content-center align-items-center">
        <div class="col-12 col-md-7">
          <!--RD Mailform-->
          <form class="rd-mailform text-left" data-form-output="form-output-global" data-form-type="contact" method="post" action="bat/rd-mailform.php" novalidate="novalidate">
            <div class="row row-14 gutters-14">
              <div class="col-sm-6">
                <div class="form-wrap">
                  <label class="form-label rd-input-label" for="contact-name">Name</label>
                  <input class="form-input form-control-has-validation form-control-last-child" id="contact-name" type="text" name="name" data-constraints="@Required"><span class="form-validation"></span>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-wrap">
                  <label class="form-label rd-input-label" for="contact-phone">Phone</label>
                  <input class="form-input form-control-has-validation form-control-last-child" id="contact-phone" type="text" name="phone" data-constraints="@Required @PhoneNumber"><span class="form-validation"></span>
                </div>
              </div>
              <div class="col-12">
                <div class="form-wrap">
                  <label class="form-label rd-input-label" for="contact-message">Message</label>
                  <textarea class="form-input form-control-has-validation form-control-last-child" id="contact-message" name="message" data-constraints="@Required"></textarea><span class="form-validation"></span>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-wrap">
                  <label class="form-label rd-input-label" for="contact-email">E-Mail</label>
                  <input class="form-input form-control-has-validation form-control-last-child" id="contact-email" type="email" name="email" data-constraints="@Required @Email"><span class="form-validation"></span>
                </div>
              </div>
              <div class="col-sm-6 align-self-end">
                <div class="form-button">
                  <button class="button button-lg button-block button-primary" type="submit">Send</button>
                </div>
              </div>
            </div>
          </form>
        </div>
        <div class="col-12 col-md-4">
          <h3>Contact Info</h3>
          <address class="subtitle">Minsk<br>Makayonka 13A/16</address>
          <ul class="contact-info">
            <li><span>Telephone:</span><a href="tel:#">+375336105624</a></li>
            <li><span>E-mail:</span><a href="mailto:#">frankyjohn2014@gmail.com</a></li>
          </ul>
        </div>
      </div><a class="close-content-box" href="/">x</a>
    </div>
  </div>

{% endblock content %}
    

app/templates/index copy.html
<!DOCTYPE html>
<html class="wide" lang="en">
  <head>
    <!-- Site Title-->
    {% block title %}
     <title>Home</title>
    {% endblock title %}
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">
    <!-- Stylesheets-->
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Barlow:100,200,300,400,700">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/fonts.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <style>.ie-panel{display: none;background: #212121;padding: 10px 0;box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3);clear: both;text-align:center;position: relative;z-index: 1;} html.ie-10 .ie-panel, html.lt-ie-10 .ie-panel {display: block;}</style>
  </head>
  <body>
    <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/">
      <img src="{{ url_for('static', filename='images/ie8-panel/warning_bar_0000_us.jpg') }}" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <!-- Page-->
    <div class="page bg-image novi-background">
      <div class="preloader">
        <div class="preloader-body">
          <div class="cssload-container">
            <div class="cssload-speeding-wheel"></div>
          </div>
          <p>Loading...</p>
        </div>
      </div>
      <!-- Page Header-->
      <header class="section page-header">
        <div class="container">
          <div class="row justify-content-between align-items-end row-30">
            <div class="col-12 col-md-6"><a class="brand-logo" href="./"><img src="{{ url_for('static', filename='images/logo-default-346x62.png') }}" alt="" /></a></div>
            <div class="col-12 col-md-6 col-xl-4">
              <div class="head-title">
                <p>I am a professional specializing <br class="d-none d-md-inline-block">in programming.</p>
              </div>
            </div>
          </div>
        </div>
      </header>
      <section class="section section-xs">
        <div class="container">
          <!-- Bootstrap tabs-->
          <div class="tabs-custom tabs-horizontal tabs-corporate" id="tabs-1">
              <ul class="nav nav-tabs">
                <li class="nav-item" role="presentation"><a class="nav-link active" href="/" data-toggle="tab"><span class="nav-link-main">MyWorks</span></a></li>
                <li class="nav-item" role="presentation"><a class="nav-link" href="#tabs-1-2" data-toggle="tab"><span class="nav-link-main">about me</span></a></li>
                <li class="nav-item" role="presentation"><a class="nav-link" href="#tabs-1-3" data-toggle="tab"><span class="nav-link-main">services</span></a></li>
                <li class="nav-item" role="presentation"><a class="nav-link" href="#tabs-1-4" data-toggle="tab"><span class="nav-link-main">contacts</span></a></li>
              </ul> 
            <div class="tab-content">
              <div class="tab-pane fade show active" id="tabs-1-1">
                <div class="tabs-custom tabs-horizontal tabs-gallery hide-on-modal" id="tabs-galery">
                    {% block content %}
                      <ul class="nav nav-tabs">
                        <li class="nav-item" role="presentation"><a class="nav-link" href="{{ url_for('posts_python.python') }}" data-toggle="tab"><img src="{{ url_for('static', filename='images/gallery-01-180x180.jpg') }}" alt="" width="180" height="180"/><span>Python3</span></a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="{{ url_for('posts_flask.flask') }}" data-toggle="tab"><img src="{{ url_for('static', filename='images/gallery-02-180x180.jpg') }}" alt="" width="180" height="180"/><span>Flask</span></a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="#tabs-gallery-3" data-toggle="tab"><img src="{{ url_for('static', filename='images/gallery-03-180x180.jpg') }}" alt="" width="180" height="180"/><span>Django3</span></a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="#tabs-gallery-4" data-toggle="tab"><img src="{{ url_for('static', filename='images/gallery-04-180x180.jpg') }}" alt="" width="180" height="180"/><span>C/C#</span></a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="#tabs-gallery-5" data-toggle="tab"><img src="{{ url_for('static', filename='images/gallery-05-180x180.jpg') }}" alt="" width="180" height="180"/><span>JavaScript</span></a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="#tabs-gallery-6" data-toggle="tab"><img src="{{ url_for('static', filename='images/gallery-06-180x180.jpg') }}" alt="" width="180" height="180"/><span>React</span></a></li>
                      </ul>
                    {% endblock content %}
                  </div>
                </div>
              </div>
          </div>
          </div>
        </div>
    </section>
      <footer class="section footer-classic context-dark novi-background">
        <div class="container">
          <div class="footer-group">
            <ul class="list-inline list-inline-xs">
              <li><a class="novi-icon icon-xxs fa-facebook icon" href="#"></a></li>
              <li><a class="novi-icon icon-xxs fa-twitter icon" href="#"></a></li>
              <li><a class="novi-icon icon-xxs fa-google-plus icon" href="#"></a></li>
              <li><a class="novi-icon icon-xxs fa-vimeo icon" href="#"></a></li>
              <li><a class="novi-icon icon-xxs fa-youtube icon" href="#"></a></li>
              <li><a class="novi-icon icon-xxs fa-pinterest-p icon" href="#"></a></li>
            </ul>
            <!-- Rights-->
            <p class="rights"><span>&copy;&nbsp;</span><span class="copyright-year"></span><span>&nbsp;</span><span>.&nbsp;</span><a href="#" data-toggle="modal" data-target="#privacy">Privacy Policy</a>. Design&nbsp;by&nbsp;<a href="">frankyjohn</a></p>
          </div>
        </div>
        <!-- Coded by JeremyLuis-->
      </footer>

      <div class="modal modal-centered slideUp" id="privacy" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="content-box">
              <div class="content-box-inner">
                <div class="row">
                  <div class="col-12">
                    <h3>Privacy Policy</h3>
                    <p>Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae. Rat voleneni ullam corporis suscipit labasic ut aliquidea commodi consequatur. Aquis autem vel eum iure reprehenderit, muytasas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae.</p>
                    <p>Rat voleneni ullam corporis suscipit labasic ut aliquidea commodi consequatur. Aquis autem vel eum iure reprehenderit. Asas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae. Rat voleneni ullam corporis suscipit labasic ut aliquidea commodi consequatur. Aquis autem vel eum iure reprehenderit, muytasas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempo. Asas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae. Rat voleneni ullam corporis suscipit labasic ut aliquidea</p>
                  </div>
                </div>
              </div><a class="close-modal-content-box" href="#" data-dismiss="modal">x</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- Javascript-->
    <script src="{{ url_for('static', filename='js/core.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <!-- coded by ragnar-->
  </body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html class="wide" lang="en">
  <head>
    <!-- Site Title-->
    {% block title %}
     <title>Home</title>
    {% endblock title %}
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">
    <!-- Stylesheets-->
    <!-- <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Barlow:100,200,300,400,700"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/fonts.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <style>.ie-panel{display: none;background: #212121;padding: 10px 0;box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3);clear: both;text-align:center;position: relative;z-index: 1;} html.ie-10 .ie-panel, html.lt-ie-10 .ie-panel {display: block;}</style>
  </head>
  <body>
    <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/">
      <img src="{{ url_for('static', filename='images/ie8-panel/warning_bar_0000_us.jpg') }}" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <!-- Page-->
    <div class="page bg-image novi-background">
      <div class="preloader">
        <div class="preloader-body">
          <div class="cssload-container">
            <div class="cssload-speeding-wheel"></div>
          </div>
          <p>Loading...</p>
        </div>
      </div>
      <header class="section page-header">
        <div class="container">
          <div class="row justify-content-between align-items-end row-30">
            <div class="col-12 col-md-6"><a class="brand-logo" href="./"><img src="{{ url_for('static', filename='images/logo-default-346x62.png') }}" alt="" /></a></div>
            <div class="col-12 col-md-6 col-xl-4">
              <div class="head-title">
                <p>I am a professional specializing <br class="d-none d-md-inline-block">in programming.</p>
              </div>
            </div>
          </div>
        </div>
      </header>
      <section class="section section-xs">
        <div class="container">
          <!-- Bootstrap tabs-->
          <div class="tabs-custom tabs-horizontal tabs-corporate" id="tabs-1">
              <ul class="nav nav-tabs">
                <li class="nav-item" role="presentation"><a class="nav-link" href="/" data-toggle="tab"><span class="nav-link-main">MyWorks</span></a></li>
                <li class="nav-item" role="presentation"><a class="nav-link" href="/about_me" data-toggle="tab"><span class="nav-link-main">about me</span></a></li>
                <li class="nav-item" role="presentation"><a class="nav-link" href="/services" data-toggle="tab"><span class="nav-link-main">services</span></a></li>
                <li class="nav-item" role="presentation"><a class="nav-link" href="/contacts" data-toggle="tab"><span class="nav-link-main">contacts</span></a></li>
              </ul> 
            <div class="tab-content">
              <div class="tab-pane fade show active" id="tabs-1-1">
                <div class="tabs-custom tabs-horizontal tabs-gallery hide-on-modal" id="tabs-galery">
                    {% block content %}
                    <ul class="nav nav-tabs">
                        {% for category in categorys %}

                              <li class="nav-item" role="presentation"><a class="nav-link" href="{{ url_for('category_detail', slug=category.slug) }}" data-toggle="tab"><img src="static/{{category.path}}" alt="" width="180" height="180"/><span>{{ category.title }}</span></a></li>
                          
                        {% endfor %}
                      </ul> 
                    {% endblock content %}
                  </div>
                </div>
              </div>
          </div>
          </div>
        </div>
    </section>
      <footer class="section footer-classic context-dark novi-background">
        <div class="container">
          <div class="footer-group">
            <ul class="list-inline list-inline-xs">
              <li><a class="novi-icon icon-xxs fa-facebook icon" href="#"></a></li>
              <li><a class="novi-icon icon-xxs fa-twitter icon" href="#"></a></li>
              <li><a class="novi-icon icon-xxs fa-google-plus icon" href="#"></a></li>
              <li><a class="novi-icon icon-xxs fa-vimeo icon" href="#"></a></li>
              <li><a class="novi-icon icon-xxs fa-youtube icon" href="#"></a></li>
              <li><a class="novi-icon icon-xxs fa-pinterest-p icon" href="#"></a></li>
            </ul>
            <!-- Rights-->
            <p class="rights"><span>&copy;&nbsp;</span><span class="copyright-year"></span><span>&nbsp;</span><span>.&nbsp;</span><a href="#" data-toggle="modal" data-target="#privacy">Privacy Policy</a>. Design&nbsp;by&nbsp;<a href="">frankyjohn</a></p>
          </div>
        </div>
        <!-- Coded by JeremyLuis-->
      </footer>

      <div class="modal modal-centered slideUp" id="privacy" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="content-box">
              <div class="content-box-inner">
                <div class="row">
                  <div class="col-12">
                    <h3>Privacy Policy</h3>
                    <p>Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae. Rat voleneni ullam corporis suscipit labasic ut aliquidea commodi consequatur. Aquis autem vel eum iure reprehenderit, muytasas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae.</p>
                    <p>Rat voleneni ullam corporis suscipit labasic ut aliquidea commodi consequatur. Aquis autem vel eum iure reprehenderit. Asas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae. Rat voleneni ullam corporis suscipit labasic ut aliquidea commodi consequatur. Aquis autem vel eum iure reprehenderit, muytasas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempo. Asas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae. Rat voleneni ullam corporis suscipit labasic ut aliquidea</p>
                  </div>
                </div>
              </div><a class="close-modal-content-box" href="#" data-dismiss="modal">x</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- Javascript-->
    <script src="{{ url_for('static', filename='js/core.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <!-- coded by ragnar-->
  </body>
</html>

app/templates/section_index.html
{% extends 'index.html' %}
    {% block title %}
        <title>Main index page</title>
    {% endblock title %}

    {% block content %}
        
            <!-- Bootstrap tabs-->

    {% endblock content %}
    